[package]
name = "metro-core"
version = "0.1.0"
authors = ["Dominic Graefen <dominic.graefen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
micromath = "1.1.0"
oorandom = "11.1.2"
